version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "9000"
    volumes:
      - ./:/var/www
    depends_on:
      - database

  database:
    image: mysql:8
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: job-watcher
      MYSQL_ROOT_PASSWORD: password
